spring: 
  #连接池配置
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/datatest?&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒 
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒 
    minEvictableIdleTimeMillis: 300000

# 其他数据库
custom.datasource:
    names: ds1
    ds1.type: com.alibaba.druid.pool.DruidDataSource
    ds1.driverClassName: com.mysql.jdbc.Driver
    ds1.url:  jdbc:mysql://192.168.0.7:3306/datatest?&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
    ds1.username: root
    ds1.password: 123456

mybatis:
  #config-location: classpath:mybatis-config.xml
  type-aliases-package: com.jianglei.mstransfer.model
  mapper-locations: classpath:com/jianglei/mstransfer/mapper/*.xml
  type-handlers-package: com.jianglei.mstransfer.typehandler
  
logging:
  level:
    root: info
    level:
      sample:
        mybatis:
          mapper: info
def: 
  page_size: 20

